export default {
  Signup: "Sign up",
  Full_NAME: "Full Name",
  Email_ID: "Email ID",
  Mobile_Number: "Mobile Number",
  Password: "Password",
  signup: "SIGN UP",
  Business_Account: "Are You Business Account",
  Already_have_an_account: "Already have an account?",
  Login: "Login",
  Privacy_policies: "By Signing in you are agreed to ",
  privacy: "Privacy policies",
  and: "  and",
  Terms: "Terms & conditions.",
  looking: "What are you looking for?",
  First_aid: "First Aid& Consumables",
  Aid_Access: "AED &Accessories",
  child: "chlidren box",
  Ambulance_Box: " Ambulance_Box",
  First_box: "First Aid",
  Dependaplas: "Dependaplas Fabric Plasters…",
  AEd_box: "AED9.00",
  Aid: "Aid",
  plasters: "plasters",
  Fabric: "Dependaplas Fabric",
  bandage: "bandage",
  Selling_Product: "Top Selling Product",
  View_all: "VIEW ALL",
  Popular_Brands: "Popular Brands",
  cart: "Cart",
  Remove: "Remove",
  Aed_50: "AED85.50",
  Including_delivery: "Including delivery & other charges: AED10.00",
  Proceed_to_Checkout: "Proceed to Checkout",
  Leo_Harmon: "Leo Harmon",
  Account_Type: "Account Type",
  individual: "individual",
  Account_Settings: "Account Settings",
  Address: "Address",
  remove_your_address: "Add, Edit or remove your address",
  Other: "Other",
  Contact: "Contact us",
  quantity: "Quantity",
  Order_Successful: "Order Successful",
  Thanks_for_your_order:
    "Thanks for your order, You will receive it by Thursday, 03 Oct 2019",
  Continue_shopping: "Continue shopping",
  View_complete: "View complete order details",
};
